# Generated by Django 5.1.3 on 2026-07-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_publicuser_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='password',
        ),
    ]
