# Generated by Django 6.0.7 on 2026-08-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_publicuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
