# Generated by Django 6.0.7 on 2026-08-05 09:08

import api.models
import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_publicuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.profile_picture_upload_to, validators=[api.validators.validate_profile_picture_upload]),
        ),
    ]
