events {
}

http {
	include /etc/nginx/mime.types;
	
	resolver 127.0.0.11 valid=10s ipv6=off;
    	resolver_timeout 5s;
	
	server {

		server_name localhost;
		# listen 8080;
		listen 8080 ssl;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate /etc/nginx/certs/proxy.crt;
		ssl_certificate_key /etc/nginx/certs/proxy.key;

		location /api/auth {
		return 308 /api/auth/;
		}

		location /api/users {
		return 308 /api/users/;
		}

		location /api/movies {
		return 308 /api/movies/;
		}


		location / {
			proxy_pass http://frontend:5173;
		}

		location ^~ /api/auth/ {
			set $auth_backend auth:8443;

            		proxy_pass http://$auth_backend;
			
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		location ^~ /api/users/ {
			set $users_backend users:8443;

            		proxy_pass http://$users_backend;

			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		location ^~ /api/movies/ {
           		set $movies_backend movies:8443;

            		proxy_pass http://$movies_backend;
			
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}		
	}
}

