events {
}

http {
	include /etc/nginx/mime.types;
	server {

		server_name localhost;
		listen 8080
		# listen 8080 ssl;
		# ssl_protocols TLSv1.2 TLSv1.3;
		# ssl_certificate /etc/nginx/certs/proxy.crt;
		# ssl_certificate_key /etc/nginx/certs/proxy.key;
		location / {
			proxy_pass http://frontend:8443;
		}
	}
}

