# Generated by Django 5.1.3 on 2026-07-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
