trad = {
    "en": 
    {
        "accept_tournament_invite_success": "You have accepted the tournament invitation",
        "added_friend_success": "Successfully added the user as a friend",
        "already_invited": "is already invited",
        "cancel_match_error": "You cannot cancel this match",
        "decline_match_error": "You cannot decline this match",
        "decline_match_success": "Match declined",
        "delete_friend_success": "Successfully removed the user from your friend list",
        "does_not_exist": "does not exist",
        "email_taken_error": "This email is already taken. Already have an account? Sign in",
        "empty_password_error": "Password cannot be empty",
        "field_not_found_error": "Field not found",
        "forbidden_username_error": "This username is not allowed",
        "free_palestine": "You cannot choose a non-existent country as a username. Free Palestine!",
        "image_format_error": "Only JPG, JPEG, or PNG images are allowed",
        "image_size_error": "Image size should not exceed 5MB",
        "image_upload_error": "Could not upload the new avatar. Please try again later",
        "in_queue": "You are in the queue",
        "invalid_body_error": "Invalid request body",
        "invalid_characters_in_username_error": "Username should only contain letters, numbers, '-', '_', and '.'",
        "invalid_credentials_error": "Invalid credentials",
        "invalid_data_error": "Invalid data",
        "invalid_image_error": "Invalid image. Please upload a valid image",
        "invalid_username_error": "Invalid username:",
        "invite_duplicates_error": "Duplicates are not allowed",
        "invite_self_error": "You cannot invite yourself",
        "invite_refused_success": "You successfully refused the invitation",
        "log_time_update_success": "Successfully updated the last log time",
        "match_creation_success": "Match created successfully",
        "match_finish_success": "Match marked as finished",
        "match_update_success": "Match updated successfully",
        "missing_fields_error": "Required fields are missing",
        "new_avatar_update_error": "Could not save the new avatar. Please try again later",
        "new_avatar_update_success": "New avatar updated successfully",
        "new_friend_not_exist_error": "The specified friend does not exist",
        "not_in_queue": "You are not in the queue",
        "not_in_tournament_error": "You are not in the tournament",
        "not_part_of_tournament": "is not part of the tournament.",
        "old_password_incorrect_error": "The old password is incorrect",
        "password_mismatch_error": "Passwords do not match",
        "player_list_update_success": "Player list updated successfully",
        "request_failure": "Request failed",
        "reset_avatar_success": "Avatar reset successfully",
        "reverse_invite_error": "You cannot create a reverse invite",
        "round_not_finished_error": "The current round is not finished",
        "self_play_error": "You cannot play against yourself",
        "tournament_at_least_3_players_error": "A tournament must have at least three players",
        "tournament_left_success": "You have left the tournament",
        "tournament_not_available_error": "Tournaments are not available at the moment",
        "tournament_already_finished_error": "The tournament has already finished",
        "tournament_already_started_error": "The tournament has already started",
        "tournament_did_not_start_error": "The tournament has not started yet",
        "tournament_next_round_success": "Next round started successfully",
        "tournament_started": "Tournament has started",
        "tournament_owner":"You're the owner of the tournament",
        "unexisting_match_error": "Match does not exist",
        "update_avatar_error": "Could not update avatar. Please try again later",
        "update_avatar_success": "Avatar updated successfully",
        "update_success": "Update successful",
        "update_username_error_in_game": "Unable to update username. Please wait until you are not in a game",
        "update_username_success": "Username updated successfully",
        "user": "User",
        "user_does_not_exist_error": "User does not exist",
        "username_invalid_error": "The username provided is invalid",
        "username_taken_error": "This username is already taken",
        "in_matchmaking_queue_error": "You're in the matchmaking queue",
        "have_game_in_progress_error": "You already have a game in progress",
        "have_invite_or_game_error":"You already sent an invite or have a game in progress",
        "in_tournament_error":"'You are in a tournament",
        "pk_error": "No pk",
        "invited_player_error": "Invited player does not exist",
        "header_info_error":"Invalid header info",
        "token_expired" : "Token Expired",
        "already_friend" : "This user is already in your friendlist"
    },

    "fr": 
    {
        "accept_tournament_invite_success": "Vous avez accepté l'invitation au tournoi",
        "added_friend_success": "L'utilisateur a été ajouté comme ami avec succès",
        "already_invited": "est déjà invité",
        "cancel_match_error": "Vous ne pouvez pas annuler ce match",
        "decline_match_error": "Vous ne pouvez pas refuser ce match",
        "decline_match_success": "Match refusé",
        "delete_friend_success": "L'utilisateur a été retiré de votre liste d'amis avec succès",
        "does_not_exist": "n'existe pas",
        "email_taken_error": "Cet e-mail est déjà utilisé. Vous avez déjà un compte ? Connectez-vous",
        "empty_password_error": "Le mot de passe ne peut pas être vide",
        "field_not_found_error": "Champ non trouvé",
        "forbidden_username_error": "Ce nom d'utilisateur n'est pas autorisé",
        "free_palestine": "Vous ne pouvez pas choisir un pays inexistant comme nom d'utilisateur. Free Palestine!",
        "image_format_error": "Seules les images JPG, JPEG ou PNG sont autorisées",
        "image_size_error": "La taille de l'image ne doit pas dépasser 5 Mo",
        "image_upload_error": "Impossible de télécharger le nouvel avatar. Veuillez réessayer plus tard",
        "in_queue": "Vous êtes dans la file d'attente",
        "invalid_body_error": "Corps de la requête invalide",
        "invalid_characters_in_username_error": "Le nom d'utilisateur ne doit contenir que des lettres, des chiffres, '-', '_' et '.'",
        "invalid_credentials_error": "Identifiants invalides",
        "invalid_data_error": "Données invalides",
        "invalid_image_error": "Image invalide. Veuillez télécharger une image valide",
        "invalid_username_error": "Nom d'utilisateur invalide:",
        "invite_duplicates_error": "Les doublons ne sont pas autorisés",
        "invite_self_error": "Vous ne pouvez pas vous inviter vous-même",
        "invite_refused_success": "Vous avez refuser l'invitation avec succes",
        "log_time_update_success": "Heure de connexion mise à jour avec succès",
        "match_creation_success": "Match créé avec succès",
        "match_finish_success": "Match marqué comme terminé",
        "match_update_success": "Match mis à jour avec succès",
        "missing_fields_error": "Champs requis manquants",
        "new_avatar_update_error": "Impossible d'enregistrer le nouvel avatar. Veuillez réessayer plus tard",
        "new_avatar_update_success": "Nouvel avatar mis à jour avec succès",
        "new_friend_not_exist_error": "L'ami spécifié n'existe pas",
        "not_in_queue": "Vous n'êtes pas dans la file d'attente",
        "not_in_tournament_error": "Vous n'êtes pas dans le tournoi",
        "not_part_of_tournament": "ne fait pas partie du tournoi.",
        "old_password_incorrect_error": "L'ancien mot de passe est incorrect",
        "password_mismatch_error": "Les mots de passe ne correspondent pas",
        "player_list_update_success": "Liste des joueurs mise à jour avec succès",
        "request_failure": "La requête a échoué",
        "reset_avatar_success": "Avatar réinitialisé avec succès",
        "reverse_invite_error": "Vous ne pouvez pas créer une invitation inversée",
        "round_not_finished_error": "La manche en cours n'est pas terminée",
        "self_play_error": "Vous ne pouvez pas jouer contre vous-même",
        "tournament_at_least_3_players_error": "Un tournoi doit avoir au moins trois joueurs",
        "tournament_left_success": "Vous avez quitté le tournoi",
        "tournament_not_available_error": "Les tournois ne sont pas disponibles pour le moment",
        "tournament_already_finished_error": "Le tournoi est déjà terminé",
        "tournament_already_started_error": "Le tournoi a déjà commencé",
        "tournament_did_not_start_error": "Le tournoi n'a pas encore commencé",
        "tournament_next_round_success": "Prochaine manche commencée avec succès",
        "tournament_started": "Le tournoi a commencé",
        "tournament_owner":"Vous etes le proprio du tournoi",
        "unexisting_match_error": "Le match n'existe pas",
        "update_avatar_error": "Impossible de mettre à jour l'avatar. Veuillez réessayer plus tard",
        "update_avatar_success": "Avatar mis à jour avec succès",
        "update_success": "Mise à jour réussie",
        "update_username_error_in_game": "Impossible de mettre à jour le nom d'utilisateur. Veuillez attendre de ne plus être en jeu",
        "update_username_success": "Nom d'utilisateur mis à jour avec succès",
        "user": "L'utilisateur",
        "user_does_not_exist_error": "Cet utilisateur n'existe pas",
        "username_invalid_error": "Le nom d'utilisateur fourni est invalide",
        "username_taken_error": "Ce nom d'utilisateur est déjà pris",
        "in_matchmaking_queue_error": "Vous etes deja dans la file d'attente",
        "have_game_in_progress_error": "Vous avez deja une partie en cours",
        "have_invite_or_game_error":"Vous avez deja envoye une invition ou une partie en cours",
        "in_tournament_error":"Vous etes déja dans un tournoi",
        "pk_error": "Aucune pk",
        "invited_player_error": "Le joueur invité n'existe pas",
        "header_info_error": "Info header invalide",
        "token_expired" : "Token Expiré",
        "already_friend" : "Cet utilisateur est déjà dans votre liste d'amis",
    },

    "es": 
    {
        "accept_tournament_invite_success": "Has aceptado la invitación al torneo",
        "added_friend_success": "Usuario agregado como amigo con éxito",
        "already_invited": "ya está invitado",
        "cancel_match_error": "No puedes cancelar este partido",
        "decline_match_error": "No puedes rechazar este partido",
        "decline_match_success": "Partido rechazado",
        "delete_friend_success": "Usuario eliminado de tu lista de amigos con éxito",
        "does_not_exist": "no existe",
        "email_taken_error": "Este correo electrónico ya está en uso. ¿Ya tienes una cuenta? Inicia sesión",
        "empty_password_error": "La contraseña no puede estar vacía",
        "field_not_found_error": "Campo no encontrado",
        "forbidden_username_error": "Este nombre de usuario no está permitido",
        "free_palestine": "No puedes elegir un país inexistente como nombre de usuario. ¡Palestina libre!",
        "image_format_error": "Solo se permiten imágenes en formato JPG, JPEG o PNG",
        "image_size_error": "El tamaño de la imagen no debe superar los 5 MB",
        "image_upload_error": "No se pudo subir el nuevo avatar. Inténtalo de nuevo más tarde",
        "in_queue": "Estás en la cola",
        "invalid_body_error": "Cuerpo de la solicitud inválido",
        "invalid_characters_in_username_error": "El nombre de usuario solo debe contener letras, números, '-', '_' y '.'",
        "invalid_credentials_error": "Credenciales inválidas",
        "invalid_data_error": "Datos inválidos",
        "invalid_image_error": "Imagen no válida. Por favor, sube una imagen válida",
        "invalid_username_error": "Nombre de usuario inválido:",
        "invite_duplicates_error": "No se permiten duplicados",
        "invite_self_error": "No puedes invitarte a ti mismo",
        "invite_refused_success": "Has rechazado la invitación con éxito",
        "log_time_update_success": "Hora de inicio de sesión actualizada con éxito",
        "match_creation_success": "Partido creado con éxito",
        "match_finish_success": "Partido marcado como terminado",
        "match_update_success": "Partido actualizado con éxito",
        "missing_fields_error": "Faltan campos obligatorios",
        "new_avatar_update_error": "No se pudo guardar el nuevo avatar. Inténtalo de nuevo más tarde",
        "new_avatar_update_success": "Nuevo avatar actualizado con éxito",
        "new_friend_not_exist_error": "El amigo especificado no existe",
        "not_in_queue": "No estás en la cola",
        "not_in_tournament_error": "No estás en el torneo",
        "not_part_of_tournament": "no forma parte del torneo.",
        "old_password_incorrect_error": "La contraseña anterior es incorrecta",
        "password_mismatch_error": "Las contraseñas no coinciden",
        "player_list_update_success": "Lista de jugadores actualizada con éxito",
        "request_failure": "Solicitud fallida",
        "reset_avatar_success": "Avatar restablecido con éxito",
        "reverse_invite_error": "No puedes crear una invitación inversa",
        "round_not_finished_error": "La ronda actual no ha terminado",
        "self_play_error": "No puedes jugar contra ti mismo",
        "tournament_at_least_3_players_error": "Un torneo debe tener al menos tres jugadores",
        "tournament_left_success": "Has abandonado el torneo",
        "tournament_not_available_error": "Los torneos no están disponibles en este momento",
        "tournament_already_finished_error": "El torneo ya ha terminado",
        "tournament_already_started_error": "El torneo ya ha comenzado",
        "tournament_did_not_start_error": "El torneo aún no ha comenzado",
        "tournament_next_round_success": "La siguiente ronda ha comenzado con éxito",
        "tournament_started": "El torneo ha comenzado",
        "tournament_owner":"You're the owner of the tournament",
        "unexisting_match_error": "El partido no existe",
        "update_avatar_error": "No se pudo actualizar el avatar. Inténtalo de nuevo más tarde",
        "update_avatar_success": "Avatar actualizado con éxito",
        "update_success": "Actualización exitosa",
        "update_username_error_in_game": "No se puede actualizar el nombre de usuario. Por favor, espera hasta que no estés en una partida",
        "update_username_success": "Nombre de usuario actualizado con éxito",
        "user": "Usuario",
        "user_does_not_exist_error": "El usuario no existe",
        "username_invalid_error": "El nombre de usuario proporcionado es inválido",
        "username_taken_error": "Este nombre de usuario ya está en uso",
        "in_matchmaking_queue_error": "Ya estás en la cola",
        "have_game_in_progress_error": "Ya tienes un partido en curso",
        "have_invite_or_game_error": "Ya has enviado una invitación o tienes un partido en curso",
        "in_tournament_error": "Ya estás en un torneo",
        "pk_error": "No pk",
        "invited_player_error": "Jugador invitado no existe",
        "header_info_error":"Inválido Cabecera info",
        "token_expired" : "Identificador Vencido",
        "already_friend" : "Este usuario ya está en tu lista de amigos",
    }

}

def translate(lang, message, parameters = None):
    '''
    lang = language (en, es, fr)
    message = key of the map
    parameters = username (for example) + more if 
    '''
    if lang == None : lang = 'en'
    if parameters is not None:
        t = trad[lang]
        traduction = ' '.join([t[message], parameters[0], t[parameters[1]] if len(parameters)>1 else ""]).rstrip()
        return traduction
    return trad[lang][message]


# if __name__ == "__main__":
    # number_inputs = int(input())
    # for _ in range(number_inputs):
        # to_trad = input().split()
        # print("English Translation:")
        # print(translate("en",to_trad[0],to_trad[1:] if len(to_trad) > 1 else None))
        # print("French Translation:")
        # print(translate("fr",to_trad[0],to_trad[1:] if len(to_trad) > 1 else None))
        # print("Spanish Translation:")
        # print(translate("es",to_trad[0],to_trad[1:] if len(to_trad) > 1 else None))
        # print()
# 