# Generated by Django 6.0.7 on 2026-09-21 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies_app', '0002_delete_legacy_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('normalized_title', models.CharField(db_index=True, editable=False, max_length=512)),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('overview', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, max_length=512)),
                ('backdrop_url', models.URLField(blank=True, max_length=512)),
                ('rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='Length in minutes.', null=True)),
                ('directors', models.JSONField(blank=True, default=list)),
                ('producers', models.JSONField(blank=True, default=list)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('original_language', models.CharField(blank=True, max_length=8)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=16)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('popularity', models.BigIntegerField(db_index=True, default=0)),
                ('metadata_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched')], db_index=True, default='pending', max_length=16)),
                ('metadata_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='MergedMovie',
            fields=[
                ('old_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_ids', to='movies_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('username', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies_app.movie')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('archive', 'Internet Archive'), ('pdt', 'Public Domain Torrents')], max_length=16)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('item_url', models.URLField(max_length=512)),
                ('downloads', models.BigIntegerField(default=0)),
                ('details_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='movies_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('unavailable', 'Unavailable')], db_index=True, default='pending', max_length=16)),
                ('origin', models.CharField(blank=True, max_length=32)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies_app.movie')),
            ],
            options={
                'ordering': ('language',),
            },
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrent_url', models.URLField(max_length=1024)),
                ('video_format', models.CharField(blank=True, max_length=16)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torrents', to='movies_app.sourceitem')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_torrent_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('progress', models.FloatField(default=0)),
                ('download_rate', models.PositiveIntegerField(default=0, help_text='Bytes per second.')),
                ('num_peers', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('local_path', models.CharField(blank=True, max_length=1024)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_offset', models.BigIntegerField(blank=True, null=True)),
                ('piece_length', models.PositiveIntegerField(blank=True, null=True)),
                ('buffered_bytes', models.BigIntegerField(default=0, help_text='Contiguous bytes available from the start.')),
                ('needs_transcode', models.BooleanField(default=False)),
                ('requested_offset', models.BigIntegerField(blank=True, null=True)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('storage_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download', to='movies_app.movie')),
                ('torrent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='movies_app.torrent')),
            ],
        ),
        migrations.CreateModel(
            name='WatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('first_watched_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='movies_app.movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sourceitem',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_source_item'),
        ),
        migrations.AddConstraint(
            model_name='subtitle',
            constraint=models.UniqueConstraint(fields=('movie', 'language'), name='unique_movie_subtitle'),
        ),
        migrations.AddConstraint(
            model_name='torrent',
            constraint=models.UniqueConstraint(fields=('source', 'torrent_url'), name='unique_source_torrent'),
        ),
        migrations.AddConstraint(
            model_name='watchrecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'movie'), name='unique_user_movie_watch'),
        ),
    ]
