# Generated by Django 6.0.7 on 2026-09-23 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='renditions_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='download',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Rendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('storage_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='movies_app.download')),
            ],
            options={
                'ordering': ('-height',),
                'constraints': [models.UniqueConstraint(fields=('download', 'height'), name='unique_download_rendition')],
            },
        ),
    ]
