# Generated by Django 6.0.7 on 2026-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=128)),
                ('lastname', models.CharField(blank=True, max_length=128)),
                ('avatar', models.CharField(blank=True, default='', max_length=256)),
                ('preferredLanguage', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=2)),
            ],
        ),
    ]
