# Generated by Django 6.0.7 on 2026-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profilePic',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
