# Generated by Django 6.0.7 on 2026-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_publicuser_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='publicuser',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
