events {
}

user www-data www-data;

http {
	include /etc/nginx/mime.types;
	server {
		root /var/www/hypertube_frontend;
		listen 8443;
		# ssl_protocols TLSv1.2 TLSv1.3;
		# ssl_certificate /etc/nginx/certs/frontend.crt;
		# ssl_certificate_key /etc/nginx/certs/frontend.key;
        	# ssl_trusted_certificate /etc/nginx/certs/ca.crt;
		location / {
			rewrite ^/(.*)/$ /$1 permanent;
			index index.html;
		}
	}
}