events {
}

user www-data www-data;

http {
	include /etc/nginx/mime.types;
	server {
		listen 8443;
		root /var/www/hypertube_frontend;
		
		location / {
			rewrite ^/(.*)/$ /$1 permanent;
			index index.html;
		}
	}
}